### ISSUE TITLE
Text wrapping happens when entering the text, not when rendering.

### ISSUE THREAD

**Issue by Dykam** [Dykam/tabbychat#29] opened 2014-02-21 02:35 UTC
![Example](https://f.cloud.github.com/assets/63073/2226325/ac6e9084-9aa0-11e3-9832-f75ead470e23.png)

**Comment by mattmess1221** [comment] 2014-02-21 04:14
For me, it only happens when I change the size of the chat box.  New messages appear as expected.

**Comment by Dykam** [comment] 2014-02-21 04:16
Yes, that is indeed the case. Which I meant. I don't recall if it resizes it when resizing in 1.10, but I think it did. This fix can probably be integrated with the fix for #28.

**Comment by mattmess1221** [comment] 2014-02-21 04:23
Yes, this was in 1.10. This will likely get low priority.

**Comment by ghost** [comment] 2014-02-27 21:42
I believe the issue is directly related to the timestamps before the chat message. I find that the warping that does happen, while does exceed the edge of the defined area, does stop after about the same length of characters as the Timestamp preceding every message.

http://i.imgur.com/XZMw5D6.png
BAI1

**Comment by mattmess1221** [comment] 2014-02-27 21:53
I have timestamps disabled and it still does that.

**Comment by mattmess1221** [comment] 2014-03-02 07:09
Anyway, fixed.

**Comment by Dykam** [comment] 2014-03-03 03:21
It still happens for me on a fresh build. Wide window, long sentence, resize window to make it shorter than the sentence, and it sticks past the window.

**Comment by mattmess1221** [comment] 2014-03-03 03:45
What I fixed was the issue @BAI1 mentioned, then.

**Comment by Brottweiler** [comment] 2014-06-16 14:57
Is this related to this issue? I think when there is room for a word, but that words happens to be too long, it goes outside the border
![](http://i.imgur.com/i0lGxKJ.png)

**Comment by insert3coins** [comment] 2014-07-03 02:46
my text over shoots the border of tabby chat like above picture but it keeps on going so yea there's no text wrapping

**Comment by mattmess1221** [comment] 2014-11-14 05:18
I discovered a temporary fix.  When this happens, just fiddle with some vanilla chat settings.  Mainly chat width. It will cause the chat to be refreshed.

**Comment by mattmess1221** [comment] 2014-12-02 22:44
Fixed via https://github.com/killjoy1221/tabbychat/commit/8b92c579ed2e120cf744843ce9c6c7817d670d8d

**Closed as completed by mattmess1221** 2014-12-02 22:44 UTC
Labels: bug
